export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_DATA_LOADED = 'CATEGORY_DATA_LOADED';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CATEGORY_UPDATE_REQUESTED = 'CATEGORY_UPDATE_REQUESTED';
export const CATEGORY_DATA_REQUESTED = 'CATEGORY_DATA_REQUESTED';
export const API_ERRORED = 'API_ERRORED';